### ISSUE TITLE
Create a WordPress.org banner image

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-force-featured-image#1]
Two sizes are needed : 772x250 and 1544x500 for retina.

**Comment by jonathanbardo** [comment]
First try on the subject :
![wordpress__force_featured_image__wordpress_plugins](https://f.cloud.github.com/assets/1933681/1461472/bbee5eca-44b2-11e3-8558-828e1ebb25ed.png)

Any advices?
/cc @westonruter @johnregan3

**Comment by westonruter** [comment]
Looks pretty cool!

**Comment by jonathanbardo** [comment]
There is another, bolder version :

![wordpress__force_featured_image__wordpress_plugins-2](https://f.cloud.github.com/assets/1933681/1461569/428f75d8-44bb-11e3-913b-316e83ca731e.png)

Credit to my girlfriend for those two versions.

**Comment by westonruter** [comment]
I do like the bolder one, except I think the triangle could be moved to not overlay the X, and the camera icon could be centered, as @johnregan3 pointed out.

**Comment by jonathanbardo** [comment]
Here is another version :
![wordpress__force_featured_image__wordpress_plugins-4](https://f.cloud.github.com/assets/1933681/1467521/cf171696-4583-11e3-824f-9919a1010331.png)
